query ArticlesGql($sort: String, $order: Order, $limit: Int, $offset: Int) {
  articles(sort: {sort: $sort, order: $order}, page: { limit: $limit, offset: $offset }) {
    nodes {
      id,
      title,
      body,
      description,
      thumbnailImage,
      postedAt,
      updatedAt
    },
    pageInfo {
      page,
      paginationLength,
      hasNextPage,
      hasPreviousPage
    }
  }
}
